version: "3"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: "177.7.0.0/16"

# 设置mysql，redis持久化保存
volumes:
  mysql:
  redis:
  mali_log:

services:
#  web:
#    build:
#      context: ./web
#      dockerfile: ./Dockerfile
##      image: luckyhacking/mali-web:latest
#    container_name: gva-web
#    restart: always
#    ports:
#      - '8080:8080'
#    depends_on:
#      - server
#    command: [ 'nginx-debug', '-g', 'daemon off;' ]
#    networks:
#      network:
#        ipv4_address: 177.7.0.11

#  server:
#    build:
#      context: ./server
#      dockerfile: ./Dockerfile
##      image: luckyhacking/mali-server:latest
#    container_name: gva-server
#    restart: always
#    volumes:
#      - mali_log:/server/log
#    ports:
#      - '8888:8888'
#    depends_on:
#      - mysql
#      - redis
#    links:
#      - mysql
#      - redis
#    networks:
#      network:
#        ipv4_address: 177.7.0.12
  mysql:
    image: mysql:8.0.20
    container_name: gva-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "13306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'gva' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: 'Aa@6447985' # root管理员用户密码
      LANG: C.UTF-8
    volumes:
      - mysql:/var/lib/mysql
    networks:
      network:
        ipv4_address: 177.7.0.13

  redis:
    image: redis:6.2
    container_name: gva-redis # 容器名
    restart: always
    ports:
      - '16379:6379'
    volumes:
      - redis:/data
    #      - ../../data/lm/redis:/data
    networks:
      network:
        ipv4_address: 177.7.0.14
