aliyun-oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  access-key-id: LTAIWFipvgiNMSuH
  access-key-secret: 3wCvdrBkatDIZYIZYAjktXQIkKpocS
  bucket-name: jeffcott
  bucket-url: https://jeffcott.oss-cn-beijing.aliyuncs.com
  base-path: mali
autocode:
  server-request: /model/%s/request/
  root: /Users/lhgtqb7bll/Downloads/mali
  server: /server
  server-api: /api/v1/%s
  server-initialize: /initialize
  server-model: /model/%s
  server-router: /router/%s
  server-service: /service/%s
  web: /web/src
  web-api: /api
  web-form: /view
  web-table: /view
  transfer-restart: true
aws-s3:
  bucket: hhacking
  region: auto
  endpoint: https://96540bd100b82adba941163704660c31.r2.cloudflarestorage.com
  secret-id: beab647508ecd650f9de54b89d534015
  secret-key: 05db374023894a52659b5e08bcff20cea691e624901ff2ca459f8a53f27c4e48
  base-url: https://cdn.wrss.top
  path-prefix: mali
  s3-force-path-style: false
  disable-ssl: false
captcha:
  key-long: 4
  img-width: 240
  img-height: 80
casbin:
  model-path: ./resource/rbac_model.conf
cors:
  mode: whitelist
  whitelist:
  - allow-origin: example1.com
    allow-methods: GET, POST
    allow-headers: content-type
    expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
      Content-Type
    allow-credentials: true
  - allow-origin: example2.com
    allow-methods: GET, POST
    allow-headers: content-type
    expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
      Content-Type
    allow-credentials: true
db-list:
- db-name: ""
  type: ""
  alias-name: ""
  path: ""
  port: ""
  config: ""
  username: ""
  password: ""
  log-mode: ""
  max-idle-conns: 10
  max-open-conns: 100
  disable: false
  log-zap: false
email:
  to: xxx@qq.com
  from: xxx@163.com
  host: smtp.163.com
  secret: xxx
  nickname: test
  port: 465
  is-ssl: true
excel:
  dir: ./resource/excel/
hua-wei-obs:
  path: you-path
  bucket: you-bucket
  endpoint: you-endpoint
  access-key: you-access-key
  secret-key: you-secret-key
jwt:
  signing-key: 7a7332e7-70a6-4a17-af03-01a263068fb2
  issuer: qmPlus
  expires-time: 604800
  buffer-time: 86400
local:
  path: uploads/file
mysql:
  path: 127.0.0.1
  port: "13306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gva
  username: root
  password: Aa@6447985
  log-mode: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-zap: false
pgsql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  log-mode: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-zap: false
qiniu:
  zone: ZoneHuaDong
  bucket: ""
  img-path: ""
  access-key: ""
  secret-key: ""
  use-https: false
  use-cdn-domains: false
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 0
system:
  env: public
  db-type: mysql
  oss-type: aws-s3
  addr: 8888
  iplimit-count: 15000
  iplimit-time: 3600
  use-multipoint: false
  use-redis: false
tencent-cos:
  bucket: xxxxx-10005608
  region: ap-shanghai
  secret-id: xxxxxxxx
  secret-key: xxxxxxxx
  base-url: https://gin.vue.admin
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server
timer:
  spec: '@daily'
  detail:
  - tableName: sys_operation_records
    compareField: created_at
    interval: 2160h
  - tableName: jwt_blacklists
    compareField: created_at
    interval: 168h
  start: true
zap:
  level: info
  format: console
  prefix: MALI
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  show-line: true
  log-in-console: true
